version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ application port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: "your_secret_cookie"  # Set your secret Erlang cookie
      RABBITMQ_DEFAULT_USER: "admin"  # RabbitMQ username
      RABBITMQ_DEFAULT_PASS: "admin"  # RabbitMQ password
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
